backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "public/images" 
public_folder: "public/images"
collections:
  - name: "addData"
    label: "addData"
    files:
      - file: "src/data/imageList.json"
        label: "addComments"
        name: "addComments"
        fields:
          - label: addComments
            name: addComments
            widget: list
            fields:
              - label: key
                name: key
                widget: text
              - label: when
                name: when
                widget: text
              - label: where
                name: where
                widget: text