backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "public/images" 
public_folder: "public/images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/data/imageList.json"
        label: "Photos"
        name: "photos"
        fields:
          - label: Photos
            name: photos
            widget: list
            fields:
              - label: box_added
                name: box_added_image
                widget: image
              - label: cropped
                name: cropped_image
                widget: image
              - label: overall
                name: overall_image
                widget: image
              - label: key
                name: key
                widget: text
              - label: when
                name: when
                widget: text
              - label: where
                name: where
                widget: text